version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:3.9

jobs:
  build:
    executor: alpine
    steps:
      - checkout
      - run:
          name: Hello World!
          command: echo 'Hello World!'

workflows:
  version: 2

  default:
    jobs:
      - build
